<?php

$this->headScript()->appendFile($this->basePath() . '/js/admin/lib/daterangepicker/moment.js');
$this->headScript()->appendFile($this->basePath() . '/js/admin/lib/daterangepicker/daterangepicker.js');
$this->headLink()->appendStylesheet($this->basePath() . '/js/admin/lib/daterangepicker/daterangepicker-bs3.css');

$this->headScript()->appendFile($this->basePath() . '/js/admin/datetime-range.js');

/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$errors = $viewModel->getVariable('errors', []);

$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Input text'));
}

$name = $viewModel->getVariable('name');

$placeholder = $viewModel->getVariable('placeholder');
if (!$placeholder) {
    $placeholder = 'Enter ' . strtolower($label);
}

$value = $viewModel->getVariable('value');
$class = $viewModel->getVariable('class');

$greaterThen = $viewModel->getVariable('greaterThen');
$lessThen = $viewModel->getVariable('lessThen');

$horizontal = $viewModel->getVariable('horizontal');

$range = '';
if (!empty($greaterThen) && !empty($lessThen)) {
    $range = $greaterThen . " - " . $lessThen;
}

?>

<div class="form-group <?= (!empty($errors)) ? 'has-error' : ''; ?> <?= $class ?>">
    <label class="<?= (!empty($horizontal)) ? 'col-sm-4 control-label' : ''; ?>"><?= $label ?></label>
    <?php if (!empty($horizontal)): ?>
        <div class="col-sm-8">
    <?php endif; ?>
    <div class="input-group">
        <div class="input-group-addon">
            <i class="fa fa-clock-o"></i>
        </div>
        <input type="text" class="form-control datetime-range pull-right" id="<?= $name ?>" name="<?= $name ?>" value="<?= $range ?>"/>
        <input type="hidden" id="<?= $name ?>_greaterThan" name="<?= $name ?>_greaterThan"/>
        <input type="hidden" id="<?= $name ?>_lessThan" name="<?= $name ?>_lessThan"/>
    </div>
    <?php if (!empty($errors)): ?>
        <?php if (is_array($errors)): ?>
            <p class="help-block"><?= implode('<br/> ', $errors); ?></p>
        <?php else: ?>
            <p class="help-block"><?= $errors ?></p>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!empty($horizontal)): ?>
        </div>
    <?php endif; ?>
</div>