<?php
/** @var \Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$label = $viewModel->getVariable('label');
$tabId = $viewModel->getVariable('tabId');
$selected = $viewModel->getVariable('selected');
$action = '';
if ($viewModel->getVariable('actionRoute')) {
    $action = $this->url(
        $viewModel->getVariable('actionRoute'),
        $viewModel->getVariable('actionRouteOptions', [])
    );
}
?>

<!-- without data-toggle="tab"-->
<li class="<?= $selected ?>">
    <a href="<?= $action ?>" aria-expanded="true"><?= $label ?></a>
</li>
