<?php
/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$errors = $viewModel->getVariable('errors', []);

$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Is checked'));
}

$name = $viewModel->getVariable('name');
$value = $viewModel->getVariable('value');
$checkedValue = $viewModel->getVariable('checkedValue', 1);
$uncheckedValue = $viewModel->getVariable('uncheckedValue', 0);
?>

<div class="form-group<?= (!empty($errors)) ? ' has-error' : ''; ?>">
    <div class="checkbox">
        <label>
            <input type="hidden" name="<?= $name ?>" value="<?= $checkedValue ?>">
            <input type="checkbox" name="<?= $name ?>" value="<?= $uncheckedValue ?>" <?= (!empty($value)) ? 'checked' : '' ?>>
            <?= $label ?>
        </label>
    </div>
    <?php if (!empty($errors)): ?>
        <p class="help-block"><?=implode('<br/> ', $errors);?></p>
    <?php endif; ?>
</div>