<?php
/** @var T4webAdmin\View\Model\CreateViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$formViewModel = $viewModel->getFormViewModel();
$formViewModel->setValues($viewModel->getInputData());
$formViewModel->setErrors($viewModel->getErrors());
?>

<section class="content-header">
    <h1>Create new entity</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <?= $this->render($formViewModel) ?>
            </div>
        </div>
    </div>
</section>
