<?php
$viewModel = $this->viewModel()->getCurrent();

$formViewModel = $viewModel->getChild('form');
$formViewModel->setVariable('errors', $viewModel->getVariable('changesErrors', []));
$formViewModel->setVariable('values', $viewModel->getVariable('changes', []));
$formViewModel->setVariable('criteria', $viewModel->getVariable('criteria', []));
?>

<section class="content-header">
    <h1><?= $viewModel->getVariable('title', 'Update entity') ?></h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <?= $this->render($formViewModel) ?>
            </div>
        </div>
    </div>
</section>
