<?php
/** @var T4webAdmin\View\Model\BaseViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entity = $viewModel->getVariable('entity');

$formViewModel = $viewModel->getChild('t4web-admin-view-component-form');
$formViewModel->setVariable('entity', $entity);

?>

<section class="content-header">
    <h1><?= $viewModel->getVariable('title') ?></h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <?= $this->render($formViewModel) ?>
            </div>
        </div>
    </div>
</section>
