<?php
$viewModel = $this->viewModel()->getCurrent();
$criteria = $viewModel->getVariable('criteria', []);
?>

<section class="content-header">
    <h1><?= $viewModel->getVariable('title', 'Delete entity confirmation') ?></h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-body">
                    <a class="btn btn-default"
                       href="<?= $this->url($viewModel->getVariable('listRoute')) ?>">
                        Back to list
                    </a>
                    <a class="btn btn-danger"
                       href="<?= $this->url($viewModel->getVariable('deleteRoute'), ['id' => $criteria['id']]) ?>">
                        <i class="fa fa-times"></i>
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
