<?php
/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$errors = $viewModel->getVariable('errors', []);

$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Input text'));
}

$name = $viewModel->getVariable('name');

$placeholder = $viewModel->getVariable('placeholder');
if (!$placeholder) {
    $placeholder = 'Enter ' . strtolower($label);
}

$value = $viewModel->getVariable('value');
$class = $viewModel->getVariable('class', '');
?>

<div class="form-group <?= (!empty($errors)) ? 'has-error' : ''; ?> <?=$class?>">
    <label><?= $label ?></label>
    <input name="<?= $name ?>" type="text" placeholder="<?= $placeholder ?>" value="<?= $value ?>" class="form-control">
    <?php if (!empty($errors)): ?>
        <?php if (is_array($errors)): ?>
            <p class="help-block"><?=implode('<br/> ', $errors);?></p>
        <?php else: ?>
            <p class="help-block"><?=$errors?></p>
        <?php endif; ?>
    <?php endif; ?>
</div>
