<?php
/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
die(var_dump(__FILE__, $viewModel));

$errors = $viewModel->getVariable('errors', []);

$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Input text'));
}

$name = $viewModel->getVariable('name');

$placeholder = $viewModel->getVariable('placeholder');
if (!$placeholder) {
    $placeholder = 'Enter ' . strtolower($label);
}

$value = $viewModel->getVariable('value');
?>

<div class="form-group<?= (!empty($errors)) ? ' has-error' : ''; ?>">
    <label><?= $label ?></label>
    <input name="<?= $name ?>" type="text" placeholder="<?= $placeholder ?>" value="<?= $value ?>" class="form-control">
    <?php if (!empty($errors)): ?>
        <p class="help-block"><?=implode('<br/> ', $errors);?></p>
    <?php endif; ?>
</div>
