<?php
/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$errors = $viewModel->getVariable('errors', []);

$label = $viewModel->getVariable('label');
if (!$label) {
    $label = ucfirst($viewModel->getVariable('name', 'Text'));
}

$name = $viewModel->getVariable('name');

$placeholder = $viewModel->getVariable('placeholder');
if (!$placeholder) {
    $placeholder = 'Enter ' . strtolower($label);
}

$value = $viewModel->getVariable('value');
?>

<div class="form-group<?= (!empty($errors)) ? ' has-error' : ''; ?>">
    <label><?= $label ?></label>
    <textarea name="<?= $name ?>" rows="3" placeholder="<?= $placeholder ?>" class="form-control"><?= $value ?></textarea>
    <?php if (!empty($errors)): ?>
        <p class="help-block"><?=implode('<br/> ', $errors);?></p>
    <?php endif; ?>
</div>
