<?php
$formViewModel = $this->viewModel()->getCurrent();

$errors = $formViewModel->getVariable('errors');

$values = $formViewModel->getVariable('values');
$criteria = $formViewModel->getVariable('criteria');
$controller = $formViewModel->getVariable('controller', 'create');
$submitText = $formViewModel->getVariable('submitText', 'Create');

$submitRouteOptions = [];
if (isset($criteria['id'])) {
    $submitRouteOptions = ['id' => $criteria['id']];
}
?>

<form
    method="post"
    action="<?= $this->url($formViewModel->getVariable('submitRoute'), $submitRouteOptions) ?>"
    enctype="<?= $formViewModel->getVariable('enctype', 'application/x-www-form-urlencoded') ?>" >
    <div class="box-body">
        <?php foreach ($formViewModel->getChildren() as $children): ?>
            <?php
            if (isset($errors[$children->getVariable('name')])) {
                $children->setVariable('errors', $errors[$children->getVariable('name')]);
            }
            if (isset($values[$children->getVariable('name')])) {
                $children->setVariable('value', $values[$children->getVariable('name')]);
            }
            ?>
            <?= $this->render($children) ?>
        <?php endforeach; ?>
    </div>
    <div class="box-footer">
        <button type="submit" class="btn btn-success" style="margin: 10px 10px"><?= $submitText ?></button>
        <?php if ($formViewModel->getVariable('cancelRoute')): ?>
            <a class="btn btn-default" href="<?= $this->url($formViewModel->getVariable('cancelRoute')) ?>">Cancel</a>
        <?php endif; ?>
    </div>
</form>