<?php
/** @var T4webAdmin\View\Model\TableHeadViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$columnsViewModels = $viewModel->getColumnsViewModels();
?>

<tr>
    <?php
    /** @var T4webAdmin\View\Model\TableHeadColumnViewModel $columnViewModel */
    foreach ($columnsViewModels as $columnViewModel) {
        echo $this->render($columnViewModel);
    }
    ?>
    <td>Actions</td>
</tr>
