<?php
/** @var T4webAdmin\View\Model\TableViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entities = $viewModel->getVariable('collection');

$rowViewModel = $viewModel->getChild('table-head');

?>

<?php if (!count($entities)): ?>
    <p class="lead">Entities not found</p>
<?php else: ?>
    <table class="table" style="table-layout:fixed;">
        <?= $this->render($rowViewModel); ?>
        <?php
            /** @var $entity T4webDomainInterface\EntityInterface */
            foreach ($entities as $entity) {
                $rowViewModel = $viewModel->getChild('table-row');
                $rowViewModel->setVariable('entity', $entity);

                echo $this->render($rowViewModel);
            }
         ?>
    </table>
<?php endif; ?>
