<?php
$viewModel = $this->viewModel()->getCurrent();
$entity = $viewModel->getVariable('entity');
?>
<tr>
    <?php
        $i = 0;
        foreach ($viewModel->getChildren() as $child) {
            $i++;

            $fieldName = $child->getVariable('field', 'Field ' . $i);
            $child->setVariable('value', $entity[$fieldName]);

            echo $this->render($child);
        }
    ?>
    <td>
        <a class="btn btn-primary btn-xs"
           href="<?= $this->url($viewModel->getVariable('readRoute'), ['id' => $entity['id']]) ?>">
            <i class="fa fa-pencil"></i>
            Edit
        </a>
        <a class="btn btn-danger btn-xs"
           href="<?= $this->url($viewModel->getVariable('deleteRoute'), ['id' => $entity['id']]) ?>">
            <i class="fa fa-times"></i>
            Delete
        </a>
    </td>
</tr>
