<?php
/** @var T4webAdmin\View\Model\TableViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entities = $viewModel->getVariable('collection');

$rowViewModel = $viewModel->getChild('table-head');

?>

<?php if (!count($entities)): ?>
    <p class="lead">Entities not found</p>
<?php else: ?>
    <table class="table" style="table-layout:fixed;">
        <?= $this->render($rowViewModel); ?>
        <?php
            /** @var $entity T4webDomainInterface\EntityInterface */
            foreach ($entities as $entity) {
                $rowViewModel = $viewModel->getChild('table-row');
                $rowViewModel->setVariable('entity', $entity);

                echo $this->render($rowViewModel);
            }
         ?>
    </table>

    <div class="modal fade" id="deleteConfirmation" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="deleteConfirmationLabel">Confirm deleting</h4>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this entity?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <a href="#" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>

    <?php $this->headScript()->captureStart() ?>
        $('#deleteConfirmation').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var href = button.data('href'); // Extract info from data-* attributes
            var summary = button.data('summary');

            if (summary != '') {
                summary = 'Entity: ' + summary;
            }

            var modal = $(this);
            modal.find('.modal-footer a').attr('href', href);
            modal.find('.modal-body').append(summary);
        })
    <?php $this->headScript()->captureEnd() ?>
<?php endif; ?>
