<?php
/** @var T4webAdmin\View\Model\TableViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entities = $viewModel->getEntities();
?>

<?php if (!$entities->count()): ?>
    <p class="lead">Entities not found</p>
<?php else: ?>
    <table class="table" style="table-layout:fixed;">
        <?php $rowViewModel = $viewModel->getHeadView(); ?>
        <?= $this->render($rowViewModel); ?>
        <?php
            /** @var $entity T4webBase\Domain\Entity */
            foreach ($entities as $entity) {
                $rowViewModel = $viewModel->getRowView();
                $rowViewModel->setEntity($entity);

                echo $this->render($rowViewModel);
            }
         ?>
    </table>
<?php endif; ?>
