<?php
/** @var T4webAdmin\View\Model\TableRowViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entity = $viewModel->getVariable('entity');
$childrenViewModel = $viewModel->getChildren();
?>

<tr>
    <?php
        $entityRaw = $entity->extract();
        /** @var T4webAdmin\View\Model\TableColumnViewModel $columnViewModel */
        foreach ($viewModel->getChildren() as $child) {
            $fieldName = $child->getVariable('field');
            if (!array_key_exists($fieldName, $entityRaw)) {
                throw new RuntimeException(sprintf("Model %s does not have field %s", get_class($entity), $fieldName));
            }

            $child->setVariable('value', $entityRaw[$fieldName]);

            echo $this->render($child);
        }
    ?>
    <td>
        <a class="btn btn-primary btn-xs"
           href="<?= $this->url($viewModel->getVariable('readRoute'), ['id' => $entity->getId()]) ?>">
            <i class="fa fa-pencil"></i>
            Edit
        </a>
        <button class="delete-btn btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteConfirmation"
           data-href="<?= $this->url($viewModel->getVariable('deleteRoute'), ['id' => $entity->getId()]) ?>" data-summary="#<?=$entity->getId()?>">
            <i class="fa fa-times"></i>
            Delete
        </button>
    </td>
</tr>
