<?php
/** @var Zend\View\Helper\ViewModel $viewModelHelper */
$viewModelHelper = $this->viewModel();
/** @var T4webAdmin\View\Model\ListFilterViewModel $viewModel */
$viewModel = $viewModelHelper->getCurrent();
?>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Filter</h3>
    </div>
    <div class="box-body">
        <form action="<?= $this->url($viewModel->getVariable('route')) ?>" method="get">
            <?php $filter = $viewModel->getVariable('filter'); ?>

            <?php foreach ($viewModel->getChildren() as $children): ?>
                <?= $this->render($children) ?>
            <?php endforeach; ?>

            <div class="box-footer text-right">
                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> Search</button>
                <a href="<?=$this->url($viewModel->getVariable('route'))?>" class="btn btn-default"><i class="fa fa-times"></i> Clear</a>
            </div>
        </form>
    </div>
</div>