<?php
$viewModel = $this->viewModel()->getCurrent();
$value = $viewModel->getVariable('value');
$classMap = $viewModel->getVariable('classMap', []);
$textMap = $viewModel->getVariable('textMap', []);
$labelClass = '';
if (isset($classMap[$value])) {
    $labelClass = 'label label-' . $classMap[$value];
}
$labelText = $value;
if (isset($textMap[$value])) {
    $labelText = $textMap[$value];
}
?>
<td>
    <span class="<?= $labelClass ?>"><?= $labelText ?></span>
</td>
