<?php
/** @var T4webAdmin\View\Model\BaseViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
/** @var ArrayObject $collection */
$collection = $viewModel->getVariable('collection');

$filterViewModel = $viewModel->getChild('filter');
$filterViewModel->setVariable('values', $viewModel->getVariable('filter', []));

$tableViewModel = $viewModel->getChild('table');
$tableViewModel->setVariable('collection', $collection);

$paginatorViewModel = $viewModel->getChild('paginator');
?>

<section class="content-header">
    <h1><?= $viewModel->getVariable('title', 'List of entities') ?></h1>
</section>

<section class="content">

    <?= $this->render($filterViewModel) ?>

    <div class="box-body text-right">
        <a class="btn btn-primary btn-xs" href="<?= $this->url($viewModel->getVariable('newRoute')) ?>"><i class="fa fa-plus"></i> New entity</a>
    </div>

    <div class="box">
        <?php if ($viewModel->getVariable('collection')->count() > 0): ?>
            <div class="box-body no-padding">
                <?= $this->render($tableViewModel);?>
            </div>

            <div class="box-footer">
                <?= $this->render($paginatorViewModel) ?>
            </div>
        <?php else: ?>
            <div class="box-header">
                <h3 class="box-title">Entities not found</h3>
            </div>
        <?php endif; ?>
    </div>
</section>
