<?php

use T4web\Paginator\ViewModel;

/** @var ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
if (! $viewModel instanceof ViewModel) {
    throw new RuntimeException('View model nust be instance of ' . ViewModel::class);
}
$viewModel->initialize();
?>
<div class="row">
    <div class="col-xs-12">
        <div class="btn-group">
            <ul class="pagination no-margin">
                <?php if ($viewModel->isPrevBtnActive()): ?>
                    <li>
                        <a href="<?= $viewModel->getUrlForPage($viewModel->getPrevPage()) ?>">«</a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#" class="disabled">«</a>
                    </li>
                <?php endif; ?>

                <?php foreach ($viewModel->getPagesInRange() as $page): ?>
                    <li class="<?= ($viewModel->isCurrentPage($page)) ? 'active' : '' ?>">
                        <a href="<?= $viewModel->getUrlForPage($page) ?>">
                            <?= $page ?>
                        </a>
                    </li>
                <?php endforeach; ?>

                <?php if ($viewModel->canRenderLastPageBtn()): ?>
                    <li>
                        <span class="elipsis">...</span>
                    </li>
                    <li>
                        <a href="<?= $viewModel->getUrlForPage($viewModel->getLastPage()) ?>">
                            <?= $viewModel->getLastPage() ?>
                        </a>
                    </li>
                <?php endif; ?>

                <?php if ($viewModel->isNextBtnActive()): ?>
                    <li>
                        <a href="<?= $viewModel->getUrlForPage($viewModel->getNextPage()) ?>">»</a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#" class="disabled">»</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>

        <div class="btn-group">
            <?php if ($viewModel->getCount() > $viewModel->getItemsCountPerPage()): ?>
                <p class="pull-left margin">View <?=$viewModel->getItemsCountPerPage()?> from <?=$viewModel->getCount()?></p>
            <?php else: ?>
                <p class="pull-left margin">View <?=$viewModel->getCount()?></p>
            <?php endif; ?>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-default"><?=$viewModel->getItemsCountPerPage()?></button>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="<?=$viewModel->getUrlForLimit(10)?>">10</a></li>
                <li><a href="<?=$viewModel->getUrlForLimit(20)?>">20</a></li>
                <li><a href="<?=$viewModel->getUrlForLimit(50)?>">50</a></li>
                <li><a href="<?=$viewModel->getUrlForLimit(100)?>">100</a></li>
            </ul>
        </div>
    </div>
</div>