<?php
/** @var T4webAdmin\View\Model\ReadViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entity = $viewModel->getMainEntity();
?>

<section class="content-header" xmlns="http://www.w3.org/1999/html">
    <h1>Entity</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <form method="post" action="<?= $this->url($viewModel->route, ['controller' => 'update',  'id' => $entity->getId()]) ?>">
                    <div class="box-body">
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success" style="margin: 10px 10px">Update</button>
                        <a class="btn btn-default" href="<?= $this->url($viewModel->route) ?>">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
