<?php
/** @var T4webAdmin\View\Model\UpdateViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$entity = $viewModel->getMainEntity();

$formViewModel = $viewModel->getFormViewModel();
$formViewModel->setValues($viewModel->getInputData());
$formViewModel->setErrors($viewModel->getErrors());
$formViewModel->setVariable('entityId', $entity->getId());
?>

<section class="content-header">
    <h1>Edit entity</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <?= $this->render($formViewModel) ?>
            </div>
        </div>
    </div>
</section>
