<?php
/** @var Sebaks\View\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
if (! $viewModel instanceof Sebaks\View\ViewModel) {
    throw new RuntimeException('View model nust be instance of ' . Sebaks\View\ViewModel::class);
}
?>

<?=$this->doctype(); ?>
<html>
<head>
    <meta charset="UTF-8">
    <?=$this->headTitle('Admin - Qwippy');?>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="/css/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <!-- Font Awesome Icons -->
    <link href="/css/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <!-- Ionicons -->
    <link href="/css/admin/ionicons/ionicons.min.css" rel="stylesheet" type="text/css"/>
    <!-- Theme style -->
    <link href="/css/admin/AdminLTE.css" rel="stylesheet" type="text/css"/>
    <link href="/css/admin/style.css" rel="stylesheet" type="text/css"/>
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="/css/admin/skins/_all-skins.min.css" rel="stylesheet" type="text/css"/>
    <link rel="shortcut icon" href="/favicon.png">

    <?= $this->headLink(); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/js/admin/lib/html5shiv.js"></script>
    <script src="/js/admin/lib/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue">
    <!-- Site wrapper -->
    <div class="wrapper">

        <?= $this->render($viewModel->getChild('top-panel')) ?>
        <?= $this->render($viewModel->getChild('sidebar-menu')) ?>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <?= $this->render($viewModel->getChild('content')) ?>
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                See <a href="/theme/AdminLTE-2.0.5/index.html" target="_blank">whole theme</a> <b>Theme by <a href="http://almsaeedstudio.com" target="_blank">Almsaeed Studio</a>. Version</b> 2.0
            </div>
            <strong>Copyright &copy;<?=date('Y')?> <a href="http://your-domain.com" target="_blank">your-domain.com</a></strong>. All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->

    <!-- jQuery 2.1.3 -->
    <script src="/js/admin/lib/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/css/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="/js/admin/lib/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='/js/admin/lib/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/js/admin/app.min.js" type="text/javascript"></script>
    <?= $this->headScript(); ?>
    <?= $this->inlineScript(); ?>

</body>
</html>