<?php /** @var T4webAdmin\View\Model\ListViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1>List of entities</h1>
</section>
<section class="content">
    <?= $viewModel->filter ?>
    <div class="box-body text-right">
        <a class="btn btn-primary" href="<?= $this->url(
            $viewModel->getRouteName(),
            ['action' => 'new']
        ) ?>">New entity</a>
    </div>
    <div class="box">
        <div class="box-body">
            <?php if (!$viewModel->getMainCollection()->count()): ?>
                <span class="box-title">Entities not found</span>
            <?php else: ?>
                <table class="table" style="table-layout:fixed;">
                    <tr>
                        <th>#</th>



                        <th>Actions</th>
                    </tr>
                    <?php /** @var $entity T4webBase\Domain\Entity */ ?>
                    <?php foreach($viewModel->getMainCollection() as $entity): ?>
                        <tr class="list">
                            <td><?= $entity->getId() ?></td>



                            <td>
                                <a class="btn btn-primary btn-xs" href="<?= $this->url(
                                    $viewModel->getRouteName(),
                                    ['action' => 'read', 'id' => $entity->getId()]
                                ) ?>">Edit</a>
                                <a class="delete-btn btn btn-danger btn-xs" href="<?= $this->url(
                                    $viewModel->getRouteName(),
                                    ['action' => 'delete', 'id' => $entity->getId()]
                                ) ?>">
                                    <i class="fa fa-times"></i>
                                    Delete
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
                <div class="pull-right">
                    <?= $viewModel->paginator ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>
