<?php
/** @var T4webAdmin\View\Model\TableViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$entities = $viewModel->getEntities();
?>

<?php if (!$entities->count()): ?>
    <span class="box-title">Entities not found</span>
<?php else: ?>
    <table class="table" style="table-layout:fixed;">
<!--        <tr>-->
<!--            <th>#</th>-->
<!--            <th>Actions</th>-->
<!--        </tr>-->
        <?php
            $rowViewModel = $viewModel->getHeadView();

            echo $this->render($rowViewModel);
        ?>
        <?php
            /** @var $entity T4webBase\Domain\Entity */
            foreach ($entities as $entity) {
                $rowViewModel = $viewModel->getRowView();
                $rowViewModel->setEntity($entity);

                echo $this->render($rowViewModel);
            }
         ?>
    </table>
<?php endif; ?>
