<?php
/** @var T4webAdmin\View\Model\NewViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$form = $viewModel->getForm();
$form->prepare();

$form->setAttribute('action', $this->url($viewModel->route));
$form->setAttribute('method', 'post');
?>

<section class="content-header">
    <h1>Create new entity</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <?php echo $this->form($form); ?>
            </div>
        </div>
    </div>
</section>
