<?php
$viewModel = $this->viewModel()->getCurrent();
?>
<section class="content-header">
    <h1>Create new entity</h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-body">
                    <div class="box-footer">
                        <a class="btn btn-default" href="<?= $this->url($viewModel->route) ?>">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
